# E501: Line too long
# S101: flake8-bandit Use of assert detected
ignore = ["E501","B028", "S101"]

exclude = ["dist","build","venv",".venv",".tox",".git"]
line-length = 88

select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "C4",   # flake8-comprehensions
    "PT",   # flake8-pytest-style
    "S",    # flake8-bandit
    "T10",  # flake8-debugger
    "T20",  # flake8-print
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]

target-version = "py38"

[isort]
known-first-party = ["src"]